  //var test_name = "C#";
var questions = [{
    question: "Which of the following is correct about C#?",
    choices: ['C# is a modern, general-purpose, object-oriented programming language developed by Microsoft', 'C# was developed by Anders Hejlsberg and his team during the development of .Net Framework',
              'C# is designed for Common Language Infrastructure (CLI)', 'All of the above'],
    correctAnswer: 3
  },{
    question: "Which of the following is correct about Object Type in C#?",
    choices: ['The Object Type is the ultimate base class for all data types in C# Common Type System (CTS)', 'Object is an alias for System.Object class',
    'The object types can be assigned values of any other types, value types, reference types, predefined or user-defined types', 'All of the above'],
    correctAnswer: 3
  }, {
    question: "Which of the following converts a type (integer or string type) to date-time structures in C#?",
    choices: ['ToString', 'ToSingle', 'ToChar', 'ToDateTime'],
    correctAnswer: 3
  }, {
   question: "Which of the following operator determines whether an object is of a certain type in C#?",
    choices: ['?:', 'is', 'as', '*'],
    correctAnswer: 1
  }, {
    question: "Which of the following access specifier in C# allows a class to expose its member variables and member functions to other functions and objects in the current assembly?",
    choices: ['Public', 'Private', 'Protected', 'Internal'],
    correctAnswer: 3
  }, {
    question: "Which of the following is true about C# structures?",
    choices: ['Structures can have methods, fields, indexers, properties, operator methods, and events', 'Structures can have defined constructors, but not destructors',
              'You cannot define a default constructor for a structure. The default constructor is automatically defined and cannot be changed', 'All of the above'],
    correctAnswer: 3
  }, {
    question: "Which of the following is the correct about class constructor?",
    choices: ['A class constructor is a special member function of a class that is executed whenever we create new objects of that class', 'Both of the above',
              'A constructor has exactly the same name as that of class and it does not have any return type', 'None of the above'],
    correctAnswer: 1
  }, {
    question: "Dynamic polymorphism is implemented by abstract classes and virtual functions.",
    choices: ['True', 'False'],
    correctAnswer: 0
  }, {
    question: "Which of the following preprocessor directive allows creating a compound conditional directive in C#?",
    choices: ['elif', 'define', 'if', 'endif'],
    correctAnswer: 0
  }, {
    question: "Which of the following is true about System.ApplicationException class in C#?",
    choices: ['The System.ApplicationException class supports exceptions generated by application programs', 'Exceptions defined by the programmers should derive from this class',
              'Both of the above', 'None of the above'],
    correctAnswer: 2
  }];

  document.write('<script type="text/javascript" src="../js/quiz_javascript.js"></script>');
